"""Central application settings for RSPdx."""

from pathlib import Path


APP_NAME = "RSPdx"
APP_ORGANIZATION = "PLDesign"

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR_NAME = "data"
LOG_DIR_NAME = "logs"
CONFIG_DIR_NAME = "config"
RECORDINGS_DIR_NAME = "recordings"
DEFAULT_LOG_FILE_NAME = "rspdx.log"

DEFAULT_SAMPLE_RATE = 8_000_000
DEFAULT_CENTER_FREQ = 392_025_000
DEFAULT_BUFF_SIZE = 65_536
MAX_HISTORY_SIZE = 100

DEFAULT_AUDIO_RATE = 48_000
DEFAULT_FFT_FPS = 20.0
DEFAULT_SPECTRUM_TRACE_ALPHA = 0.65
DEFAULT_PERF_LOG_INTERVAL_S = 5.0
DEFAULT_WATERFALL_MAX_BINS = 32_768
DEFAULT_WATERFALL_TIME_STRIDE = 2

DEFAULT_FM_DEEMPHASIS_US = 50.0
DEFAULT_NFM_DEEMPHASIS_US = 300.0

DEFAULT_IF_GAIN = 40
DEFAULT_RF_GAIN = 15

UI_FILE_NAME = "ui_main.ui"
